import sys
import os
import pandas as pd
from tqdm import tqdm
from Bio import SeqIO
from pathlib import Path
import statistics

#commandline : python script/TAT_RGP_dynamism.py input input/core_genome/core_genome_photorhabdus_genus_features.csv input/list_genomes_dynamism.lst results/dynamism True results/TATracking_final_results.tsv


def main():

    #will maybe do a argarser later
    gff_pt_folder = sys.argv[1] #generated by the annotate step from PanACoTA
    core_features_file = sys.argv[2] #generated from TAT_core2df.py 
    list_genome_file = sys.argv[3] #list file with one genome name per line 
                                    # Note: the first genome will be used as the reference in this study
    outdir = sys.argv[4]

    resume = sys.argv[5] # default False, enter True if you want to resume a previous MMseqs analysis (it will check at which corespot it stopped)
    TATracking_file = sys.argv[6]

    #get the list of the genomes to include in the analysis.
    list_genomes = get_genomes2include(list_genome_file)

    #merge all gff file into one dataframe
    df_all_gff = concat_gff(list_genomes, gff_pt_folder)

    #get the core_genome_features into a df
    df_core_features = pd.read_csv(core_features_file, skiprows = 1, sep = "\t", names = ["core_gene_name","core_family", "genome_name", "contig", "gene_number", "left_coordinate", "right_coordinate", "strand"])
    
    df_corespot = get_genes_within_same_core_spot(df_core_features, df_all_gff, list_genomes)

    df_combined_corespot = combine_list_of_gene_list(df_corespot)
    df_combined_corespot.to_csv(f"{outdir}/corespot_all_phylogeny.tsv" ,sep = "\t")
    #now doing the families clusters using MMseqs2
    #First create a multi Index SeqIO object => with the protein files of each given genome (so we can access it to create the necessary files for the clustering)
    all_protein_SeqIO = None
    for genome in list_genomes:
        if all_protein_SeqIO == None:
            all_protein_SeqIO = SeqIO.index(f"{gff_pt_folder}/Proteins/{genome}.prt", "fasta")
        else :
             all_protein_SeqIO = MultiIndexDict( all_protein_SeqIO, SeqIO.index(f"{gff_pt_folder}/Proteins/{genome}.prt", "fasta"))

    if resume == "True":
        resume_analysis_at = check_last_corespot_mmseqs(f"{outdir}/mmseqs")
    else :
        resume_analysis_at = -1

    d_gene_cluster_per_corespot = clusters_corespot(df_combined_corespot, all_protein_SeqIO, resume_analysis_at, outdir)

    df_final = calculate_dynamism(df_combined_corespot, d_gene_cluster_per_corespot)
    df_final.to_csv(f"{outdir}/final_vdyn_calcul.tsv", sep = "\t")
    #df_final[df_final["n_total_clusters"].astype(bool)].to_csv(f"{outdir}/final_vdyn_calcul_noempty.tsv", sep = "\t")

    # if you searched for TAs in the reference genome using TATracking script, this will add to the df_final the TAs carried by each corespot
    if TATracking_file != False:
        df_TATracking = pd.read_csv(TATracking_file, sep = "\t", index_col = 0)
        df_final_with_TA = associate_corespot_TA(df_final, df_TATracking, list_genomes[0])
        df_final_with_TA.dropna(subset = ["mean_n_genes_corespot"], inplace = True)
        df_final_with_TA.to_csv(f"{outdir}/final_vdyn_calcul_withTA.tsv", sep = "\t")
        df_final_with_TA.dropna(subset = ["TA_within_corespot"], inplace = True)
        df_final_with_TA.to_csv(f"{outdir}/final_vdyn_calcul_onlyTA.tsv", sep = "\t")

def get_genomes2include(list_file):
    
    res_list = []
    with open(list_file, "r") as f:
        for line in f:
            res_list.append(line.strip())
    
    return res_list

def concat_gff(list_genomes, gff_pt_folder):

    gff_columns = ["contig", "source", "type", "left_coordinate", "right_coordinate", "dot", "strand", "0", "ID"]
    df = pd.read_csv(f"{gff_pt_folder}/gff3/{list_genomes[0]}.gff", names = gff_columns, comment = "#", sep = "\t")
    
    for genome in list_genomes[1:]:
        df = pd.concat([df, pd.read_csv(f"{gff_pt_folder}/gff3/{genome}.gff", names = gff_columns, comment = "#", sep = "\t")])

    df["ID"] = df["ID"].apply(lambda x: x.split(';')[0].split('=')[-1])
    df = df.sort_values(by = "left_coordinate")
    df["genome_name"] = df.apply(lambda x: x["contig"].rsplit(".",1)[0], axis = 1)

    return df

def get_genes_within_same_core_spot(df_core, df_all_gff, list_genomes):

    #return a dictionnary with for each core spot k = corespot number, v = {left_core_family, right_core_family, list_genes_within core spot in each genomes}
    d_res = {}
    n_index = 0
    df_core_ref = df_core[df_core["genome_name"] == list_genomes[0]].sort_values(by = "left_coordinate").reset_index(drop = True)
    df_core_others = df_core[df_core["genome_name"] != list_genomes[0]].reset_index(drop = True)
    df_all_gff = df_all_gff[df_all_gff["type"] == "CDS"]

    print("Getting all genes part of the same core spot in the whole genome dataset")
    for ref_core_gene_row in tqdm(df_core_ref.iterrows(), total = df_core_ref.shape[0]):
        tmp_list_genes = []
        ref_core_gene1 = ref_core_gene_row[1]["core_gene_name"]
        ref_family1 = ref_core_gene_row[1]["core_family"]
        left_c1 = ref_core_gene_row[1]["left_coordinate"]

        if n_index +1 < len(df_core_ref)-1:
            ref_core_gene2 = df_core_ref.iloc[n_index+1]["core_gene_name"]
            ref_family2 = df_core_ref.iloc[n_index+1]["core_family"]
            left_c2 = df_core_ref.iloc[n_index+1]["left_coordinate"]
            tmp_list_genes.append(df_all_gff[(df_all_gff["genome_name"] == list_genomes[0]) & (df_all_gff["left_coordinate"] > left_c1) & (df_all_gff["left_coordinate"] < left_c2)]["ID"].tolist())

        elif n_index == len(df_core_ref)-1: #in this case the RGP is located between the last core and the first core gene
            ref_core_gene2 = df_core_ref.iloc[0]["core_gene_name"]
            ref_family2 = df_core_ref.iloc[0]["core_family"]
            left_c2 = df_core_ref.iloc[0]["left_coordinate"]
            tmp_list_genes.append(df_all_gff[(df_all_gff["genome_name"] == list_genomes[0]) & ((df_all_gff["left_coordinate"] > left_c1) | (df_all_gff["left_coordinate"] < left_c2))]["ID"].tolist())

        for genome in list_genomes[1:]:
            new_ref_core1 = df_core_others[(df_core_others["genome_name"] == genome) & (df_core_others["core_family"] == ref_family1)]["core_gene_name"].values[0]
            new_ref_core2 = df_core_others[(df_core_others["genome_name"] == genome) & (df_core_others["core_family"] == ref_family2)]["core_gene_name"].values[0]
            new_left_c1 = df_core_others[(df_core_others["genome_name"] == genome) & (df_core_others["core_family"] == ref_family1)]["left_coordinate"].values[0]
            new_left_c2 = df_core_others[(df_core_others["genome_name"] == genome) & (df_core_others["core_family"] == ref_family2)]["left_coordinate"].values[0]

            #checking if in this genome, the two core genes are the last and the first in this genome
            tmp_first_core = df_core_others[df_core_others["genome_name"] == genome].reset_index(drop = True).iloc[0]["core_gene_name"]
            tmp_last_core = df_core_others[df_core_others["genome_name"] == genome].reset_index(drop = True).iloc[-1]["core_gene_name"]
            
            if new_ref_core1 in [tmp_first_core,tmp_last_core] and new_ref_core2 in [tmp_first_core,tmp_last_core]:
                 list_genes_this_genome = df_all_gff[(df_all_gff["genome_name"] == genome) & ((df_all_gff["left_coordinate"] > max(new_left_c1,new_left_c2)) | (df_all_gff["left_coordinate"] < min(new_left_c1,new_left_c2)))]["ID"].tolist()

            else : #most cases
                list_genes_this_genome = df_all_gff[(df_all_gff["genome_name"] == genome) & (df_all_gff["left_coordinate"] > min(new_left_c1,new_left_c2)) & (df_all_gff["left_coordinate"] < max(new_left_c1,new_left_c2))]["ID"].tolist()

            #added a checkpoint to determine if indeed the two corresponding core genes are the closest ones in this genome
            res_check_nocore_in_genelist = check_nocore_in_genelist(list_genes_this_genome, df_core_others)
            if  res_check_nocore_in_genelist == True:
                tmp_list_genes.append(list_genes_this_genome)

            else :
                #write in a error log file which core genes was found in the given list
                with open("tmp/TAT_RGP_dynamism_errorlogs.txt", "a") as f:
                    f.write(f"The given corespot (core families : {ref_family1}/{ref_family2}) changed in the following genome {genome} \n The gene {res_check_nocore_in_genelist} was detected as part of the core genome in the following given list. \n genelist : list_genes_this_genome")

        d_res[n_index] = {"core_family_1": ref_family1, "core_family_2": ref_family2, "min_coordinate_ref_genome": min(left_c1, left_c2), "max_coordinate_ref_genome": max(left_c1, left_c2), "list_of_genelist": tmp_list_genes}


        n_index += 1

    df_res = pd.DataFrame.from_dict(d_res, orient = "index")
    return df_res


        
def check_nocore_in_genelist(list_genes, df_core):

    for gene in list_genes :
        if gene in df_core["core_gene_name"].tolist():
            return gene
    
    return True

def combine_list_of_gene_list(df_corespot):

    df_corespot["number_genes"] = df_corespot.apply(lambda x: count_genes_in_list(x["list_of_genelist"]) ,axis =1)
    df_corespot["all_genes_ref"] = df_corespot.apply(lambda x: x["list_of_genelist"][0] , axis =1)
    df_corespot["all_genes_list"] = df_corespot.apply(lambda x: unpacklist(x["list_of_genelist"]) , axis =1)

    return df_corespot


def count_genes_in_list(listoflist):

    res = []
    for x in listoflist:
        res.append(len(x))

    return res

def unpacklist(listoflist):
    res = []
    for x in listoflist:
        res+=x
    
    return res

def clusters_corespot(df_combined_corespot, all_protein_SeqIO, resume_analysis_at, outdir) :

    #For each corespot, we first need to create two fasta files, one with the protein sequences of the reference genome, and the others one with the others genes
    n_corespot = int(resume_analysis_at) #useful to name the mmseqs file
    print(f"Performing the MMseqs analysis for each corespot: starting/resuming at corespot number : {n_corespot+1}")
    df_combined_corespot = df_combined_corespot.iloc[n_corespot+1: , :] #slicing the dataframe so we can resume the analysis at the last corspot mmseqs done

    for corespot_row in tqdm(df_combined_corespot.iterrows(), total = df_combined_corespot.shape[0]):
        n_corespot += 1
        if is_mmseqs_necessary(corespot_row[1]["number_genes"]) == False :
            continue
        else :
            create_tmp_mmseqs_files(corespot_row[1]["all_genes_list"], all_protein_SeqIO)
            os.system(f"mmseqs easy-cluster tmp/tmp_mmseqs2_all_seqs.fasta results/dynamism/mmseqs/{n_corespot}_corespot tmp -v 0 --remove-tmp-files True")

    #time to count the total number of cluster
    d_gene_cluster_per_corespot = {}
    for mmseq_tsv in Path(f"{outdir}/mmseqs").glob("*.tsv"):
        d_gene_cluster_per_corespot[int(mmseq_tsv.stem.split("_",1)[0])] = analysis_mmseqs(mmseq_tsv)

    return d_gene_cluster_per_corespot

def is_mmseqs_necessary(list_number_genes):

    #check if at least two genomes have at least one gene within this corespot 
    if sum(1 for genes_number in list_number_genes if genes_number >= 1) < 2:
        return False
    
    elif sum(1 for genes_number in list_number_genes if genes_number >= 1) >= 2:
        return True


def create_tmp_mmseqs_files(list_all_genes, all_protein_SeqIO):

    with open(f"tmp/tmp_mmseqs2_all_seqs.fasta", "w") as f:
        for gene in list_all_genes:
            f.write(f">{gene}\n{all_protein_SeqIO[gene].seq}\n")


def analysis_mmseqs(mmseq_tsv):

    #getting the total number of different genes families in the corespot
    #update the d_res for each core spot k = n_corespot, v = number of total families
    df_mmseqs_corespot = pd.read_csv(mmseq_tsv, sep = "\t", names = ["representative", "match"])
    #determine if we need to consider a gene duplicated in the same genome
    df_duplicates = df_mmseqs_corespot[df_mmseqs_corespot["representative"] != df_mmseqs_corespot["match"]]
    
    if df_duplicates.empty == False :
        df_duplicates["duplicated_gene"] = df_duplicates.apply(lambda x: True if x.representative.rsplit(".",1)[0] == x.match.rsplit(".",1)[0] else False, axis = 1)
        return int(len(df_duplicates[df_duplicates["duplicated_gene"] == True]) + len(df_mmseqs_corespot["representative"].drop_duplicates()))

    else :
        return int(len(df_mmseqs_corespot["representative"].drop_duplicates()))



def check_last_corespot_mmseqs(outdir_mmseqs_folder):
    
    list_of_mmseqs_files = Path(outdir_mmseqs_folder).glob("*.tsv")
    return max((Path(mmseq_file).stem.split("_")[0] for mmseq_file in list_of_mmseqs_files), key = lambda mmseq_file: int(Path(mmseq_file).stem.split("_")[0]))


def calculate_dynamism(df, d_gene_cluster_per_corespot):
    df = df.drop(columns = ["list_of_genelist","all_genes_ref", "all_genes_list"])

    for k, v in d_gene_cluster_per_corespot.items():
        df.loc[k, "n_total_clusters"] = v
        df.loc[k, "median_n_genes_corespot"] = statistics.median(df.loc[k, "number_genes"])
        df.loc[k, "mean_n_genes_corespot"] = statistics.mean(df.loc[k, "number_genes"])
        if statistics.median(df.loc[k, "number_genes"]) != 0:
            df.loc[k, "v_dyn (= n_total_clusters)/mediane(number_genes)"] = v/statistics.median(df.loc[k, "number_genes"])
        else :
            df.loc[k, "v_dyn (= n_total_clusters)/mediane(number_genes)"] = "NaN"
    
    return df


def associate_corespot_TA(df_final, df_TATracking, ref_genome):

    df_TATracking_ref = df_TATracking[df_TATracking["Genome"] == ref_genome].drop_duplicates(subset = "Ref_TA")
    df_TATracking_ref[["tox_left_coordinate"]] = df_TATracking_ref[["tox_left_coordinate"]].apply(pd.to_numeric)
    df_res = df_final.copy()

    for corespot_row in df_final.iterrows():
        if df_TATracking_ref[(df_TATracking_ref["tox_left_coordinate"] > int(corespot_row[1]["min_coordinate_ref_genome"])) & (df_TATracking_ref["tox_left_coordinate"] < int(corespot_row[1]["max_coordinate_ref_genome"]))].empty == False:
            df_res.loc[corespot_row[0], "TA_within_corespot"] = ",".join(df_TATracking_ref[(df_TATracking_ref["tox_left_coordinate"] > int(corespot_row[1]["min_coordinate_ref_genome"])) & (df_TATracking_ref["tox_left_coordinate"] < int(corespot_row[1]["max_coordinate_ref_genome"]))]["Ref_TA"].tolist())

    return df_res


################################################################################################################

class MultiIndexDict:
    def __init__(self, *indexes):
        self._indexes = indexes
    def __getitem__(self, key):
        for idx in self._indexes:
            try:
                return idx[key]
            except KeyError:
                pass
        raise KeyError("{0} not found".format(key))





if __name__ == "__main__":
    main()