import pandas as pd
import sys
import os


#just a little script which create a dataframe/tsv file with all the coordinates of cores genes within a same file 
#useful in others of my script to determine the localization of TA 
#it needs the core file(corepers step : 100%) & the directory with gff files(annotate step) generated by PanACoTA

#commandline : python script/core2df.py input/core_genome/core_genome_photorhabdus_genus.lst input/photorhabdus_genus_gff input/core_genome/core_genome_photorhabdus_genus_features.csv

def main():

    core_file = sys.argv[1]
    gff_directory = sys.argv[2]
    outfile = sys.argv[3]

    #first we create a dictionnary with store for each core gene (from every genome)
    d_core = corepers2df(core_file)

    #now for every gene in this dict we open the genome file and get the features of the core gene
    list_core = []
    list_genome = []
    for k,v in d_core.items():
        list_core.append(k)
        if v["genome_name"] not in list_genome:
            list_genome.append(v["genome_name"])
    
    gff_columns = ["contig","source","type", "left_coordinate", "right_coordinate", "dot", "strand", "0" ,"description"]

 
    for g in list_genome:
        df_tmp = pd.read_csv(f"{gff_directory}/{g}.gff", sep = "\t", comment = "#", names = gff_columns)
        df_tmp["description"] = df_tmp["description"].apply(lambda x: x.split(';')[0].split('=')[-1])

        for gene, d_gene in d_core.items():
            if d_gene["genome_name"] == g:
                d_core[gene]["left_coordinate"] = df_tmp[df_tmp["description"] == gene]["left_coordinate"].item()
                d_core[gene]["right_coordinate"] = df_tmp[df_tmp["description"] == gene]["right_coordinate"].item()
                d_core[gene]["strand"] = df_tmp[df_tmp["description"] == gene]["strand"].item()

    df_core = pd.DataFrame.from_dict(d_core, orient = "index")
    df_core.to_csv(outfile, sep ="\t")

def corepers2df(file2df):

    #return a dataframe with index = gene name, columns: comparative genomic family / number of genes in this family /Genome name / number of the ORF gene
    d={}
    with open(file2df, "r") as f:
        for line in f:
            for i in range(1, len(line.split(" "))):
                d[line.split(" ")[-i].strip()] = {"core_family": line.split(" ")[0], "genome_name": line.split(" ")[-i].rsplit("_",1)[0][:-6],
                                                "contig": line.split(" ")[-i].rsplit("_",1)[0][:-1], "gene_number": int(line.split(" ")[-i].rsplit("_",1)[1]) }

    return d



if __name__ == "__main__":
    main()